# Generated by Django 4.1 on 2023-10-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField(max_length=15)),
                ('balance', models.PositiveIntegerField()),
                ('sponsored', models.PositiveIntegerField()),
                ('company', models.CharField(max_length=100, null=True)),
                ('sponsor_type', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy'), ('Yuridik shaxs', 'Yuridik')], max_length=100)),
                ('status', models.CharField(choices=[('MODERATION', 'Moderatsiya'), ('NEW', 'Yangi'), ('APPROVED', 'Tasdiqlangan'), ('CANCELED', 'Bekor qilingan')], default='MODERATION', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('BACHELOR', 'Bakalavr'), ('MAGISTER', 'Magister')], max_length=100)),
                ('contract', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
